### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by ged** [ged/ruby-pg#296]
**[Original report](https://bitbucket.org/ged/ruby-pg/issue/296) by Vít Ondruch (Bitbucket: [vo_x](https://bitbucket.org/vo_x), ).**

----------------------------------------

Result of static analysis pointed out this unreachable code:

```
Error: UNREACHABLE (CWE-561): [#def19]
pg-1.0.0/usr/share/gems/gems/pg-1.0.0/ext/pg_connection.c:3613: unreachable: This code cannot be reached: "enc_inspect = rb_inspect(enc);".
# 3611|   	}
# 3612|   
# 3613|-> 	enc_inspect = rb_inspect(enc);
# 3614|   	rb_raise( rb_ePGerror, "unknown encoding: %s", StringValueCStr(enc_inspect) );
# 3615|   
```

**Comment by larskanis** [comment]
Fixed by commit https://github.com/ged/ruby-pg/commit/f2d22ee0840cae619fb8aea3eee39c0be4aba550
