### ISSUE TITLE
wait_socket_readable locks up forever on DNS failover

### ISSUE THREAD

**Issue by ged** [ged/ruby-pg#297]
**[Original report](https://bitbucket.org/ged/ruby-pg/issue/297) by Jeff Wallace (Bitbucket: [tjwallace](https://bitbucket.org/tjwallace), GitHub: [tjwallace](https://github.com/tjwallace)).**

----------------------------------------

We've been testing failover with PostgresQL on Aiven, and noticed that when DNS failover happens, active queries get stuck. It looks like it's coming from `wait_socket_readable` and then `rb_wait_for_single_fd`. Here is some debugging output: [https://gist.github.com/tjwallace/ddd12ae8ffb03c248f8aa22af9ab8789](https://gist.github.com/tjwallace/ddd12ae8ffb03c248f8aa22af9ab8789).

I’m not sure if this is a ruby-pg issue or a ruby issue, but thought I’d drop it here as a start.

**Comment by larskanis** [comment]
A lot of IO code has changed in both ruby-pg and in ruby, so I'll close this issue now.
