### ISSUE TITLE
PG::ConnectionBad at /

### ISSUE THREAD

**Issue by ged** [ged/ruby-pg#299]
**[Original report](https://bitbucket.org/ged/ruby-pg/issue/299) by BeeRich33 (Bitbucket: [Rich](https://bitbucket.org/Rich), GitHub: [Rich](https://github.com/Rich)).**

----------------------------------------

I have a `Sinara` `before` `SELECT` request that’s tripping out after the app is set for a non-restart. Refreshes minutes after this happens, I get this bad connection. I just updated my `rbenv` to 2.6.2 from 2.5.1. After a manual restart, and all I can think of, this happens.

Under the 2.5.1 version, an hourly refresh of this page happens, and I’ve never seen this error before.

## ‌ PQconsumeInput\(\) server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request.

```
res = $conn.exec_params( %Q{ SELECT count(id) FROM s_ads_t WHERE status = $1 }, ['new'] )
```

No output on the troubleshooting output at all.

I have `Postico` which connects just fine to both local workstation and the remote server \(non-SSL\).

**Comment by daBee** [comment]
Was an **exec-params** asynchronous issue.  So it's acting as expected.  My fault.  

Can you close this?.

**Comment by larskanis** [comment]
Ok, thanks for the update!
