### ISSUE TITLE
Update rubygems links

### ISSUE THREAD

**Issue by graudeejs** [ged/ruby-pg#304]
https://rubygems.org/gems/pg

Many links on RubyGems gem page refer to BitBucket.
Please update links to Github.

**Comment by cbandy** [comment]
More than #303?

**Comment by graudeejs** [comment]
:man_facepalming:

**Comment by cbandy** [comment]
This should probably stay open until RubyGems has the correct links. @larskanis do you have credentials there?

**Comment by larskanis** [comment]
I think most of the links will be updated when a new gem is pushed. Otherwise I'll update it manually.

**Comment by ged** [comment]
Last i checked it wasn't possible to edit manually, though it used to be. I've pushed 1.2.0, which updated the links.
