### ISSUE TITLE
Support for target_session_attrs

### ISSUE THREAD

**Issue by raivil** [ged/ruby-pg#305]
Does this gem support `target_session_attrs` as defined on https://www.postgresql.org/docs/12/libpq-connect.html? I couldn't find anything on the docs.

If not, is there a plan/timeline to support it?

Best Regards,

**Comment by larskanis** [comment]
You can define any of listed parameters here: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS
In addition we [already improved our documentation](https://github.com/ged/ruby-pg/commit/658325023c78b6e7424296ddac322d618f9bec33) on master branch and describe only positional parameters and link to libpq's description for all other parameters.

**Comment by raivil** [comment]
Awesome. Thank you for the quick answer!
