### ISSUE TITLE
CentOS 7 Can't find the PostgreSQL client library (libpq)

### ISSUE THREAD

**Issue by zhongw** [ged/ruby-pg#314]
Installed postgresql 11 on CentOS 7 by yum (official), facing ```Can't find the PostgreSQL client library (libpq)``` when gem install pg, the log files attached, could anyone facing the same issue? 
any help will be appriciate.

[mkmf.log](https://github.com/ged/ruby-pg/files/3959460/mkmf.log)
[gem_make.log](https://github.com/ged/ruby-pg/files/3959461/gem_make.log)

**Comment by simi** [comment]
Which system package have you installed? I think you need `postgresql-devel` or `libpq-dev` (depends on your system version). Can you check if any of those packages is installed? Do you have `pg_config` available in your PATH (according to log you do not have, it should be part of one of those system packages mentioned).

**Comment by zhongw** [comment]
please close this issue, it should be the environment issue.
