### ISSUE TITLE
New release 1.1.5?

### ISSUE THREAD

**Issue by junaruga** [ged/ruby-pg#317]
Is it possible to release current master as version 1.1.5?

Because you and we fixed some issues after version 1.1.4 that was released at January 09, 2019.

And there is no warning in the Travis log of current master branch. That's great. Thank you for the work.
https://travis-ci.org/ged/ruby-pg/jobs/626133420#L623

On Fedora Project, there is a `pg`'s RPM package that I am working for.
https://kojipkgs.fedoraproject.org//packages/rubygem-pg/1.1.4/4.fc32/data/logs/x86_64/build.log
And I want to suppress some warnings in the RPM building environment.

```
BUILDSTDERR: /builddir/build/BUILD/pg-1.1.4/usr/share/gems/gems/pg-1.1.4/lib/pg/connection.rb:50: warning: URI.regexp is obsolete
```

**Comment by larskanis** [comment]
pg-1.2.0 is ready to be shipped. @ged will do in the next days.

**Comment by junaruga** [comment]
Oh alright. Thank you for that.

**Comment by ged** [comment]
Just pushed 1.2.0. Thanks for your patience, all.

**Comment by junaruga** [comment]
Thank you!
