### ISSUE TITLE
Incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by meap** [ged/ruby-pg#318]
After upgrade to latest `ruby-pg` 1.20, I am encountering with the following error:

>Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8

The rest environment has not been changed, and the issue is related to the upgrade of the gem. Do you have an idea what could be wrong?

Ruby 2.6.5 (tested also on 2.7), Postgres 10 (tested also on 11), Sequel  and Sequel_pg in the latest versions.

Stack trace: https://gist.github.com/meap/0d6712712eb9f8a912394b443f878e7d

**Comment by bitencode** [comment]
Having the same issue, downgraded back to pg 1.1 and everything is working fine 😕. I tested on Ruby 2.6.3 and Postgres 10 and 12, Sequel 5.27.0 (latest) and Sequel_pg 1.12.2 (latest).

**Comment by larskanis** [comment]
This is actually an issue of sequel_pg. I filed a report here: https://github.com/jeremyevans/sequel_pg/issues/34

Could you please try to remove sequel_pg from the Gemfile and retry with pg-1.2.0?

**Comment by meap** [comment]
Yes, you're right. It works without `sequel_pg`.

**Comment by bitencode** [comment]
Agreed, pg-1.2.0 works fine when sequel_pg is not used.

**Comment by larskanis** [comment]
sequel_pg-1.12.4 and pg-1.2.1 fix this. Thank you @jeremyevans !
