### ISSUE TITLE
Low performance, high CPU usage when using TCP sockets (1.2.2)

### ISSUE THREAD

**Issue by olieidel** [ged/ruby-pg#329]
I spent this morning debugging this issue, here are my findings - hopefully I save other people some time :)

My ruby-fu is quite limited so let me know if I should provide any additional information.

### Versions

* OS: macOS Mojave 10.14.6
* Postgres 12.1
* Ruby 2.6.5
* Rails 6.0.2.1

### Procedure

1. Create a rails application with `rails new --database=postgresql` which implicitly fetches the `pg` gem with version `1.2.2`.
2. Looking into `config/database.yml`, rails by default uses unix sockets to connect to the postgres db - good. Everything works well in that case. However, in this case I add the config parameter `host: localhost`, thereby forcing it to use TCP sockets, useful e.g. when using a dockerized postgres instance.
3. Any operation touching the db, e.g. `rails db:drop`, takes very long now. Profiling it, it seems to hang at `PG::Connection#initialize` at 100% CPU for around 10-15s (normal: 1-2s).
4. This happens both on a local postgres install (via homebrew) and on a dockerized one.
5. Using a unix socket instead (homebrew postgres) fixes it.
6. Rolling `pg` back to `1.2.1` also fixes it.

So the only thing I know for sure is that it's due to some change in `1.2.2`. Of course I can't exclude the possibility that something's awry with my local setup.

Let me know if I can help! And keep up the good work! :)

**Comment by olieidel** [comment]
It gets weirder. Now I also saw this behaviour with `1.2.1`. I had uninstalled postgres in the meantime via ´brew uninstall postgresql` (but still had `libpq` installed) and was using a dockerized postgres instance.

Re-installing postgres via `brew install postgres` seemes to have fixed it and `1.2.2` is now also working. Don't ask me why.

Closing for now, this seems to be some local problem.

**Comment by larskanis** [comment]
There's quite sure no change between [pg-1.2.1 and 1.2.2](https://github.com/ged/ruby-pg/compare/v1.2.1...v1.2.2) that is related to your issue. Did you solve it in the meantime?

**Comment by olieidel** [comment]
I still had been running `1.2.1.` for now. Just tried `1.2.2` again - it seems to be fixed, for no apparent reason.

It remains mysterious, but happy to close this for now as apparently I'm the only one affected. Chances are, it's a problem on my side.
