### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _PQresultMemorySize

### ISSUE THREAD

**Issue by chmich** [ged/ruby-pg#333]
pg-gem seems to search the wrong dylib

installed on mac osx

postgres installed by postgres-installer (not homebrew)

[stackoverflow](https://stackoverflow.com/questions/59846019/rails-postgres-dyld-lazy-symbol-binding-failed-symbol-not-found-pqresultme/60513513#60513513)

thanks!
chris

**Comment by larskanis** [comment]
Dupe of #332
