### ISSUE TITLE
Question: Release date of version 1.2.3

### ISSUE THREAD

**Issue by junaruga** [ged/ruby-pg#334]
Hello, thank you for maintaining `pg`.

Seeing [History.rdoc](https://github.com/ged/ruby-pg/blob/master/History.rdoc) v1.2.3 part, do you know when the version 1.2.3 will be released?

**Comment by ecbrodie** [comment]
I am also a little confused by this. If version 1.2.3 is not yet released, then wouldn't it make more sense to list banked-up changes into an "Unreleased" section of the History.md file? Or at least note that this version number is not yet released?

**Comment by ged** [comment]
@ecbrodie : Would you also expect the code in the `master` branch to not include "banked-up changes"? What would the point of a version-control system be? You can always track what's in the latest release via the version tag.

@junaruga : I'll be releasing it today.

**Comment by ecbrodie** [comment]
When I see a version number in the changelog, I tend to think that this
version has been shipped to a central package repository already, in this
case being rubygems.

Not sure where your questioning of the existence of a version control
system came from.

Anyway, this is just my feedback. Feel free to use it as you wish.

**Comment by ged** [comment]
v1.2.3 should now be on the gem servers.

@ecbrodie : Maybe we can just use a placeholder instead of the date in the history for the upcoming release. I find value in having a running log of what version we're anticipating for the next release as well as what will be in it with the current format, but I can see how having a date in it is misleading. Anyway, thanks for the feedback.

**Comment by junaruga** [comment]
@ged Thanks! I can see [the v1.2.3 on RubyGems](https://rubygems.org/gems/pg).
I think you need to run `git tag` for the version to this repository.

**Comment by ged** [comment]
Oops, forgot to `git push --tags`. Done now. Thanks for the heads-up!
