### ISSUE TITLE
Question: Are there any compatibility issues with PostgreSQL 11?

### ISSUE THREAD

**Issue by hkim3162** [ged/ruby-pg#335]
I am currently on pg -v 0.21.0 and upgrading to postgresql 11. Can we upgrade ruby-pg to the most recent version without issues? How about keeping the version to 0.21.0?

**Comment by larskanis** [comment]
It should work. There haven't been any breaking changes between PostgreSQL 9.6 and 11, as far as I know.
However please also consider to upgrade to a more recent version of pg.
