### ISSUE TITLE
Problem installing gem on OpenSUSE leap 15.1

### ISSUE THREAD

**Issue by ngetahun** [ged/ruby-pg#340]
Hi,
I am having issues installing pg on my OpenSUSE Leap 15.1. I have postgres 10 installed.

PG gem version: `1.2.2`
Postgres version: `postgres (PostgreSQL) 10.12`
OpenSUSE version: `openSUSE Leap 15.1`
Ruby version: `2.5.8`
Is version `1.2.2` compatible with postgres 10.
Error message screenshot:
![Screenshot_20200513_142304](https://user-images.githubusercontent.com/9084637/81812327-42c93580-9526-11ea-97b8-ba074916b408.png)

**Comment by cbandy** [comment]
`PQERRORS_SQLSTATE` is provided by the PostgreSQL client header files: https://github.com/postgres/postgres/blob/master/src/interfaces/libpq/libpq-fe.h#L117

I think you need to install package `postgresql10-devel` or so.

**Comment by ngetahun** [comment]
The flag `PGERRORS_SQLSTATE` flag is only available on postgresql 12. This is a backward compatibility problem.

**Comment by larskanis** [comment]
This constant is added when libpq provides [PostgreSQL-12 specific functions](https://github.com/ged/ruby-pg/blob/master/ext/pg.c#L464). So you seems to have a PostgreSQL-12 library, but older header files.

**Comment by ngetahun** [comment]
The problem in my case was outdated `libpq` versions. I will close this issue now.
