### ISSUE TITLE
We are observing a 10-30% regression in aggregate SQL execution time in v1.2.3 in some cases.

### ISSUE THREAD

**Issue by kitsunde** [ged/ruby-pg#343]
I haven't devised a test for this yet because I'm not sure what to test exactly, but we monitor our SQL execution times. Specifically, with [prometheus_exporter](https://github.com/discourse/prometheus_exporter) we collect durations of SQL execution on each endpoint by hooking into `PG::Connection` in Rails:

```ruby
MethodProfiler.patch(PG::Connection, [
  :exec, :async_exec, :exec_prepared, :send_query_prepared, :query
], :sql)
```

When we upgraded from 1.2.2 to 1.2.3 we observe the following:

<img width="953" alt="Screenshot 2020-07-21 22 30 12" src="https://user-images.githubusercontent.com/48965/88068303-9b5e2400-cba2-11ea-9ce1-3fbbec121f67.png">

<img width="942" alt="Screenshot 2020-07-21 22 30 04" src="https://user-images.githubusercontent.com/48965/88068294-98fbca00-cba2-11ea-86c8-b8228c42aff6.png">

When we reverted the change the reverse happens:

<img width="997" alt="Screenshot 2020-07-21 22 40 03" src="https://user-images.githubusercontent.com/48965/88068712-25a68800-cba3-11ea-9b04-5e09654e745a.png">

<img width="1009" alt="Screenshot 2020-07-21 22 39 36" src="https://user-images.githubusercontent.com/48965/88068702-22130100-cba3-11ea-89ed-0131c2251a34.png">

These are the execution times of 30-50 queries in each graph. Looking through the changes in 1.2.3 I'm assuming the time isn't actually spent on SQL executing in PG but rather overhead in the library itself.

We've never faced the issue with segmentation faults that the 1.2.3 release is supposed to fix despite being on ruby 2.7.x for months with a fair amount of traffic.

**Comment by larskanis** [comment]
@kitsunde Thank you for the detailed report! And sorry for the long delay!

The new pg version 1.3.0 changes a lot regarding the handling of the socket IO. It would be very interesting how your results are performance-wise!

**Comment by larskanis** [comment]
pg-1.3.0 has a new install switch which should improve the query performance a little bit, but it is not enabled per default:
```
gem inst pg -- --disable-gvl-unlock
```
or through bundler:
```
bundle config build.pg --disable-gvl-unlock
```
See here in the [History.rdoc](https://github.com/ged/ruby-pg/blob/0206294450a7edad13f79649a7cdf4cab2d9a71e/History.rdoc#v130-2022-01-20-michael-granger-gedfaeriemudorg-).
