### ISSUE TITLE
Precision lost with <-> KNN Postgis operator

### ISSUE THREAD

**Issue by Aryk** [ged/ruby-pg#346]
Here is the environment:

PG Gem: 1.2.2

Production System: 
 * Aurora Postgres on Amazon - PostgreSQL 11.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.9.3, 64-bit
 * POSTGIS="2.5.2" [EXTENSION] PGSQL="110" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 5.2.0, September 15th, 2018" GDAL="GDAL 2.3.1, released 2018/06/22" LIBXML="2.9.3" LIBJSON="0.12.99" LIBPROTOBUF="1.3.0" RASTER

```
[50] pry(main)> conn = PG.connect("postgres://postgres:<password>@blahblah.rds.amazonaws.com")
[48] pry(main)> conn.exec(%{ select "location_point" <-> 'SRID=4326;POINT(14.43280472 50.0715455)'::geography as point from users where id=335}).to_a
=> [{"point"=>"6572353.16963382"}]
```

Now, when I run it in DBeaver, I'm getting one more "2" on the result of 6572353.16963382:

<img width="912" alt="Screen Shot 2020-07-27 at 9 00 43 AM" src="https://user-images.githubusercontent.com/525212/88508595-dff51f80-cfe7-11ea-8b5c-6cb7b15ede64.png">

But in ruby-pg:

```
[56] pry(main)> conn.exec(%{ select "location_point" <-> 'SRID=4326;POINT(14.43280472 50.0715455)'::geography as point from users where "location_point" <-> 'SRID=4326;POINT(14.43280472 50.0715455)'::geography = 6572353.16963382}).to_a
=> []
```

However, if I add the "2" that I know is missing....

```
[57] pry(main)> conn.exec(%{ select "location_point" <-> 'SRID=4326;POINT(14.43280472 50.0715455)'::geography as point from users where "location_point" <-> 'SRID=4326;POINT(14.43280472 50.0715455)'::geography = 6572353.169633822}).to_a
=> [{"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"},
 {"point"=>"6572353.16963382"}]
```

Anybody know why this is happening?

This is causing issues with my token based pagination because to the database the value is 6572353.169633822, but my token is "6572353.16963382" and this is causing results to turn up twice.

**Comment by larskanis** [comment]
> This is causing issues with my token based pagination because to the database the value is 6572353.169633822, but my token is "6572353.16963382" and this is causing results to turn up twice.

Equality comparisons of floating point values are a difficult thing. They are often unreliable since floats are meant to represent analogical values and comparisons should always include a tolerance. You can google for "floating point comparison" to get more information of this topic.

To group values that are near to each other you could define the number of decimal digits to compare. This can be done with `to_char()` like so:
```sql
SELECT to_char(1234.56789e303::float8, '9.9999999EEEE');
# =>  "1.2345679e+306"
```

Another option is setting [extra_float_digits](https://www.postgresql.org/docs/12/runtime-config-client.html#GUC-EXTRA-FLOAT-DIGITS) like so:
```sql
set extra_float_digits=-3;
SELECT -1234.567890123456789e-303::float8;
# => "-1.23456789012e-300"
```
