### ISSUE TITLE
default database name

### ISSUE THREAD

**Issue by ecl66** [ged/ruby-pg#347]
This issue happens when using a database setup in which the default PostgreSQL database is named differently to "postgres". Typically, some hosted databases (ie Digital Ocean) have renamed the default admin db to "defaultdb" for example.
Therefore, it becomes impossible to use functions such as db:create, that fails with 'postgres database does not exists'.
Would it be possible to configure (for ex in database.yml) the name of the default DB?
Cheers

**Comment by larskanis** [comment]
This is probably more a question for the rails project. Could you please ask it there?
