### ISSUE TITLE
Trouble installing pg gem  on Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by mchilson** [ged/ruby-pg#351]
I am having an issue trying to install the pg gem on a clean install of Ubuntu 20.04 LTS. Postgres 12 is the default to install on this release and the compiler cannot find a header file... Here is the failing line:

Using config values from /usr/bin/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header

I could be wrong but the issue seems to be that one of the dependencies of libpq-dev is causing the issue.
I did another clean install in a VM and got the same issue.
A little more experimenting I installed Postgres 10 in a clean VM and everything worked

I have all the correct packages installed so I know I am good there (this is not my first rodeo with pg and rails).

Thoughts?

Many thanks in advance.
Mike

**Comment by mchilson** [comment]
Some additional information... 

running apt-file shows the header file should be installed with libpq-dev...

mike@mike-ws:~/apt-file search libpq-fe.h
**libpq-dev: /usr/include/postgresql/libpq-fe.h**

However, I quick listing of the "install directory" comes up empty (no such directory postgresql):

mike@mike-ws:/usr/include$ ls
aio.h        cpio.h       endian.h    fstab.h         ifaddrs.h   libxml2   mlocate        netinet     pcre2.h             pthread.h   scsi           stdio.h        thread_db.h  video
aliases.h    crypt.h      envz.h      fts.h           inttypes.h  libxslt   mntent.h       netipx      pcre2posix.h        pty.h       search.h       stdlib.h       threads.h    wait.h
alloca.h     ctype.h      err.h       ftw.h           iproute2    limits.h  monetary.h     netiucv     pcrecpparg.h        pwd.h       semaphore.h    string.h       tic.h        wchar.h
argp.h       cursesapp.h  errno.h     gcalc-2         jerror.h    link.h    mqueue.h       netpacket   pcrecpp.h           python3.8   setjmp.h       strings.h      time.h       wctype.h
argz.h       cursesf.h    error.h     gci-2           jmorecfg.h  linux     mtd            netrom      pcre.h              rdma        sgtty.h        sudo_plugin.h  ttyent.h     wordexp.h
ar.h         curses.h     eti.h       gconv.h         jpegint.h   locale.h  nc_tparm.h     netrose     pcreposix.h         readline    shadow.h       syscall.h      uchar.h      X11
arpa         cursesm.h    etip.h      getopt.h        jpeglib.h   ltdl.h    ncurses_dll.h  nfs         pcre_scanner.h      re_comp.h   signal.h       sysexits.h     ucontext.h   x86_64-linux-gnu
asm-generic  cursesp.h    execinfo.h  glob.h          langinfo.h  lzma      ncurses.h      nl_types.h  pcre_stringpiece.h  regex.h     sound          syslog.h       ulimit.h     xen
assert.h     cursesw.h    fcntl.h     gmpxx.h         lastlog.h   lzma.h    ncursesw       node        pngconf.h           regexp.h    spawn.h        tar.h          unctrl.h     yaml.h
bsd          cursslk.h    features.h  gnumake.h       libexslt    malloc.h  net            nss.h       png.h               reglib      sqlite3ext.h   termcap.h      unicode      zconf.h
byteswap.h   dirent.h     fenv.h      gnu-versions.h  libgen.h    math.h    netash         obstack.h   pnglibconf.h        resolv.h    sqlite3.h      term_entry.h   unistd.h     zlib.h
bzlib.h      dlfcn.h      finclude    grp.h           libintl.h   mcheck.h  netatalk       openssl     poll.h              rpc         stab.h         term.h         utime.h
c++          drm          fmtmsg.h    gshadow.h       libltdl     memory.h  netax25        openvpn     printf.h            rpcsvc      stdc-predef.h  termio.h       utmp.h
clang        editline     fnmatch.h   histedit.h      libpng      menu.h    netdb.h        panel.h     proc_service.h      ruby-2.7.0  stdint.h       termios.h      utmpx.h
complex.h    elf.h        form.h      iconv.h         libpng16    misc      neteconet      paths.h     protocols           sched.h     stdio_ext.h    tgmath.h       values.h

Also, pg-config reports the include files in the same directory:

mike@mike-ws:/usr/bin$ pg_config
BINDIR = /usr/lib/postgresql/12/bin
DOCDIR = /usr/share/doc/postgresql-doc-12
HTMLDIR = /usr/share/doc/postgresql-doc-12
INCLUDEDIR = /usr/include/postgresql
PKGINCLUDEDIR = /usr/include/postgresql
INCLUDEDIR-SERVER = /usr/include/postgresql/12/server
LIBDIR = /usr/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/lib/postgresql/12/lib
LOCALEDIR = /usr/share/locale
MANDIR = /usr/share/postgresql/12/man
SHAREDIR = /usr/share/postgresql/12
SYSCONFDIR = /etc/postgresql-common

Has anyone else experienced this yet?

**Comment by mchilson** [comment]
**SOLVED**

On Ubuntu 20.04.1 LTS DO NOT install the PostgreSQL and or libpq-dev packages from the Ubuntu repo they are missing several items. Go to the Postgres site and set up their repo and install it from there. Hope this helps someone else.

[https://www.postgresql.org/download/linux/ubuntu/](https://www.postgresql.org/download/linux/ubuntu/)

**Comment by ehannes** [comment]
If someone else is struggling with this: strangely enough, I had installed `postgresql` and adding the missing `libpq-dev` package solved my problem on Ubuntu 21.04.
