### ISSUE TITLE
Transient Connection spec on TruffleRuby

### ISSUE THREAD

**Issue by eregon** [ged/ruby-pg#354]
This run failed, and it looks like a transient:
https://travis-ci.org/github/ged/ruby-pg/jobs/722470256
```
  1) running with sync_* methods PG::Connection described_class#block should allow a timeout
     Failure/Error: expect( (finish - start) ).to be_within( 0.2 ).of( 0.3 )
       expected 1.002 to be within 0.2 of 0.3
     # ./spec/pg/connection_spec.rb:783:in `block (2 levels) in <top (required)>'
     # ./spec/helpers.rb:30:in `block in included'
```

@larskanis Could you restart to get an idea if it's transient?

The spec is https://github.com/ged/ruby-pg/blob/fd5ccb7dbb20722e6b2cd1aca7ef186951f2a19a/spec/pg/connection_spec.rb#L776-L784
One possibility could be that a GC happens inside the timing block.

BTW could you restart https://travis-ci.org/github/ged/ruby-pg/jobs/722470259 too? That seems a TruffleRuby bug, but I'd like to see if it's transient.

I'm noticing since those builds are making https://github.com/eregon/truffleruby-gem-tracker red.

**Comment by larskanis** [comment]
All green now! I'm going to relax the timings of the test.

**Comment by eregon** [comment]
Thanks!
