### ISSUE TITLE
Return type changed when moving from 1.0.0 -> 1.2.3

### ISSUE THREAD

**Issue by mrothenbuhler** [ged/ruby-pg#357]
Hello,

It seems like the return type of `timestamp` changed from a `String` to a `Time` object when upgrading versions, but I can't find any documentation on that, at least so far. It was a breaking change for us and we're a little confused. 

Do you know about this?

**Comment by mrothenbuhler** [comment]
Looks like this happened from 1.0.0 -> 1.1.0. The new expected behavior is that timestamp columns are now automatically converted to `Time` objects by default.

**Comment by mrothenbuhler** [comment]
Last question--is there a reason it wasn't marked as a breaking change? If the return value's type is changed

**Comment by larskanis** [comment]
pg-1.2 still returns timestamp values as strings by default. It returns a `Time` objects only when a `type_map_for_results` is active and that didn't change between 1.0 and 1.1.

Possibly you're using rails and access the raw pg output by `<attibute>_before_type_cast` ? Rails is using native pg type casts of pg-1.1+ only. But `_before_type_cast` output isn't guarantied to be consistent.

If this doesn't answer your question, please post a sample script to reproduce your issue!

**Comment by mrothenbuhler** [comment]
Thanks @larskanis ! I've narrowed it down a bit more.

I'm unfamiliar with `type_map_for_results`, but it doesn't appear anywhere in our codebase. We don't seem to use `<attibute>_before_type_cast` too often either. We are using rails.

The issue seems to have only come up around `ActiveRecord::Base.connection.execute(` statements. Using 1.0.0, timestamp fields would come back as strings and now they come back as Time objects.

The other weird thing is that when using the ruby console to test this stuff out, whether we use 1.0.0 or 1.2.3, things like `RandomModel.first.created_at` always comes back as an ActiveSupport::TimeWithZone` object. So, we're still investigating.

**Comment by mrothenbuhler** [comment]
Okay here's something very explicit and clear. This is an example from our rails console

pg -> 1.0.0
```
irb(main):002:0> res = ActiveRecord::Base.connection.execute('select * from projects limit 1')
   (1.6ms)  select * from projects limit 1
irb(main):003:0> res
=> #<PG::Result:0x0000556791083c68 status=PGRES_TUPLES_OK ntuples=1 nfields=59 cmd_tuples=1>
irb(main):009:0> res.first['updated_at'].class
=> String
```

pg -> 1.2.3
```
irb(main):001:0> res = ActiveRecord::Base.connection.execute('select * from projects limit 1')
   (1.9ms)  select * from projects limit 1
=> #<PG::Result:0x0000562367508800 status=PGRES_TUPLES_OK ntuples=1 nfields=59 cmd_tuples=1>
irb(main):002:0> res
=> #<PG::Result:0x0000562367508800 status=PGRES_TUPLES_OK ntuples=1 nfields=59 cmd_tuples=1>
irb(main):003:0> res.first['updated_at'].class
=> Time
```

**Comment by larskanis** [comment]
OK, that makes sense! `execute` returns a raw PG::Result object. Both rails and PG are consistent across release versions. But you're using two different abstraction levels of the query interface simultaneously. And Rails changes the way it makes use of PG depending on it's features (between pg-1.0 and 1.1). And since you use a raw PG::Result from rails, you get the result of this change into you application.

You can either work with the Time objects or retrieve strings by one of these two options:
```
# Open a dedicated connection to the PG server and use the PG query interface which returns strings only by default
pgconn = PG.connect(ActiveRecord::Base.connection.raw_connection.conninfo_hash.compact)
res = pgconn.exec('select * from projects limit 1')
res.first['updated_at'].class  # => String
```
That makes the PG connection completely independent from rails.

Or disable the use of rails internal type map for the particular PG::Result:
```
res = ActiveRecord::Base.connection.execute('select * from projects limit 1')
res.map_types!(PG::TypeMapAllStrings.new)
res.first['updated_at'].class  # => String
```

**Comment by larskanis** [comment]
@mrothenbuhler What is the status of this issue? Did my recommendations work?
