### ISSUE TITLE
Build fails ruby 3 linux

### ISSUE THREAD

**Issue by olegantonyan** [ged/ruby-pg#366]
openSUSE Tumbleweed 64bits pg gem fails to build with ruby 3:
```
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
```

It works fine with ruby 2, but fails with 3.0.0. I have all postgres devel packages installed, the header is there:
```
-rw-r--r-- 1 root root 23K Jan  9 03:18 /usr/include/pgsql/libpq-fe.h
```

**Comment by ryarturogi** [comment]
gem install pg -- --with-pg-dir="C:\Program Files\PostgreSQL\13" 

you need to set the dir for you PG

**Comment by junaruga** [comment]
@olegantonyan I think you can try to install `rubygem-pg` RPM or ask the maintainer of the  `rubygem-pg` about how to install `pg` gem directly. Maybe they know the proper PosgreSQL library.

https://packagehub.suse.com/packages/rubygem-pg/
https://forums.opensuse.org/showthread.php/543667-Rails-Gem-Error-while-installing-pg-(1-2-3)

**Comment by olegantonyan** [comment]
Solved by installing `postgresql13-server-devel`, even though `libpq-fe.h` exists in `postgresql13-devel` package, for some reason `postgresql13-server-devel` is also required
