### ISSUE TITLE
PG::ConnectionBad: PQconsumeInput() SSL error: tlsv1 alert protocol version

### ISSUE THREAD

**Issue by kevgrig** [ged/ruby-pg#381]
I have a really strange and annoyingly intermittent issue causing errors with symptoms such as the following (the pg gem is 1.2.3):

```
#<ActiveJob::DeserializationError: Error while trying to deserialize arguments: PG::ConnectionBad: PQconsumeInput() SSL error: tlsv1 alert protocol version>
  /var/www/html/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec'
  /var/www/html/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `block (2 levels>
  /var/www/html/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
  /var/www/html/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
  /var/www/html/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
  /var/www/html/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'
[...]
```

I captured tcpdump of the issue and the relevant packets right around the error are: [sslerror.pcap.gz](https://github.com/ged/ruby-pg/files/6633209/sslerror.pcap.gz)

This socket was open for 4 hours before hitting this issue (and I have all the way back to the handshake if needed).

Viewing the above pcap in Wireshark:

![Screenshot_20210610_101045](https://user-images.githubusercontent.com/6432587/121568145-371f9b00-c9d4-11eb-8fd8-7c2026498f52.png)

This is a managed database on Digital Ocean and it's PostgreSQL 13. The database port is 25060.

Note that if I load the entire capture of the TCP stream (170MB so I can't upload here) that includes the handshake, Wireshark shows the "Protocol" column as TLSv1.3, although just loading the cut pcap shows TLSv1.2, so I'm guessing Wireshark could only guess so much without the handshake.

Anyway, what's odd is that I don't see any TLS alert packets on that entire stream, so I don't understand why pg is complaining about "tlsv1 alert" and I don't know why it says TLSv1.

The last good packet seems to be from the pg client to the server on packet 22. However, the next packet (23) is the pg client sending a FIN. I don't understand why pg is closing the socket.

Is there any tracing I can enable in pg? Any other ideas? I've also opened a support ticket with Digital Ocean although I suspect they'll just say it's an issue with the client based on the tcpdump, as it does appear to be.

Is there something like [SSLKEYLOGFILE](https://wiki.wireshark.org/TLS#Using_the_.28Pre.29-Master-Secret) that I can enable in pg to allow me to decrypt the stream?

**Comment by kevgrig** [comment]
I tried disabling TLS with the following in database.yml:

```
  sslmode: disable
```

However Digital Ocean managed databases doesn't support non-TLS traffic:

```
FATAL:  no pg_hba.conf entry for host "10.124.0.9", user [...], SSL off
```

Next I tried to downgrade to TLS1.2 with the following in database.yml:

```
  ssl_max_protocol_version: TLSv1.2
```

This seems to have been configured correctly based on Wireshark tcpdump analysis; however, the issue still occurred.

So I guess the next step is back to tracing the error more deeply. Any suggestions on how to do this welcome.

**Comment by kevgrig** [comment]
Digital Ocean found the matching error in the PostgreSQL server logs and it shows "SSL error: wrong version":

![Screenshot_20210610_202938](https://user-images.githubusercontent.com/6432587/121626646-af18b000-ca2a-11eb-933e-26a4708df114.png)

Which doesn't make much sense becaues that socket had been working fine for 4 hours before...

**Comment by larskanis** [comment]
You can enable the trace-log on the client by adding a rails initializer like this:

```ruby
require "pg"

class PG::Connection
  alias init_before_trace initialize
  def initialize(*args, **kwargs, &block)
    conn = init_before_trace(*args, **kwargs, &block)

    fd = File.open("#{Rails.root}/log/pg_trace_#{object_id}.log", "a+")
    conn.trace(fd)

    conn
  end
end
```
The log files will probably become pretty large after 4 hours, but show you all the unencrypted commands and answers exchanged with the server. However I'm uncertain whether it will help, since the issue seems to be in the SSL layer.

**Comment by larskanis** [comment]
You can get ugly errors like the one you encountered, if a connection is used concurrently from multiple threads or processes. Usually ActiveRecord automatically takes care about thread binding and establishes a new connection for every new thread. However you might double check that the connection isn't used by a second thread (or process after fork).

Possibly it's helpful to use an initializer like the one above to wrap all relevant methods and verify that a connection is always used by a single thread only.

**Comment by kevgrig** [comment]
I ended up switching from using delayed_job (which ran in vanilla ruby processes) for running my rails ActiveJobs to using async threads for ActiveJobs inside my nginx+passenger process, and the problem has gone away. So it seems it's related to the following version of ruby, fyi:

```
$ ruby --version
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
```
