### ISSUE TITLE
Expired gem certificate

### ISSUE THREAD

**Issue by riffraff** [ged/ruby-pg#382]
Hey everyone, 

It seems the certificate associated with the gem has expired 

```
$ gem install pg -P MediumSecurity -v '1.2.3' -- --with-pg-config=/opt/local/lib/postgresql13/bin/pg_config
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=ged/DC=FaerieMUD/DC=org not valid after 2020-12-23 20:19:51 UTC
```
I can still install this with security disabled. 

I'm on macOS 11.3 (20E232) with ruby 2.7, if that matters.

**Comment by larskanis** [comment]
@ged Do you want to renew your certificate? Or shall I make future releases with my own certificate?

**Comment by ged** [comment]
I committed my latest cert, but that won't change the cert the last gem was signed by. There isn't really any provision for managing certs in the Rubygems infrastructure, so we'd have to re-release with the new cert.

**Comment by larskanis** [comment]
The gem signing cert is updated in pg-1.3.0.
