### ISSUE TITLE
Switch to bundler for building pg.gem

### ISSUE THREAD

**Issue by larskanis** [ged/ruby-pg#383]
@ged Do you agree to drop Hoe from the Rakefile and just use bundler to build the gem?

Some background:

I think bundler and gemspec files are pretty standard these days and Hoe adds a reasonable amount of duplication and complexity.

Current build on Windows fails due to a no longer allowed Regexp in `.hoerc` [here](https://ci.appveyor.com/project/larskanis/ruby-pg-xa3f5/builds/39609067/job/4r5dr4ay487avc2l#L74). I'm not sure how it is used or could be dropped entirely.

We switched to git as the canonical VCS years ago, but still have a dependency to hg by the hoe-deviate plugin through the hoe-mercurial plugin. I would like to remove them both.

I would also add some release automation like [here in ffi](https://github.com/ffi/ffi/commit/1a87af07cb6e52762f1e3316f5c956bc7538e649). It adds a git tag message taken from the `History.rdoc` and pushes all release files at once.

**Comment by ged** [comment]
Yep, makes sense to me. I had been working on removing that stuff myself, but you're doing most of the work nowadays anyway so whatever gets out of your way.
