### ISSUE TITLE
Multiple hosts are not supported because it's not a valid URI

### ISSUE THREAD

**Issue by levkk** [ged/ruby-pg#387]
Hello,

Multiple hosts, as documented by [33.1.1.3. Specifying Multiple Hosts](https://www.postgresql.org/docs/12/libpq-connect.html#LIBPQ-CONNSTRING), is not supported because the gem attempts to [parse and re-stringify](https://github.com/ged/ruby-pg/blob/master/lib/pg/connection.rb#L51) the URL before giving it to `PQconnectdb`.

Instead I think it should just pass the connection string as-is to `PQconnectdb` since that function is able to handle all the options and would give an error if the URI is not valid.

Thank you.

**Comment by larskanis** [comment]
I overhauled the connection option builder as part of #397, so that it is possible to specify multiple hosts.

The URI is no longer changed by the option hash, but we still extend it with `hostaddr` and `fallback_application_name` for convenience. I think this is a good tradeoff.
