### ISSUE TITLE
pg error on Windows 10 (Ruby 3.0)

### ISSUE THREAD

**Issue by hk-dd** [ged/ruby-pg#392]
Dear pg-Team

I'm using Ruby 3.0.2, Rails 6.1.4 on Win10.
The pg gem is successfully installed (and is shown in the gem list as 'pg (1.2.3)').

Problem:
After the 'rails s' command, the following error message appears:

C:/Ruby30-x64/lib/ruby/3.0.0/bundler/runtime.rb:69:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'pg'. (Bundler::GemRequireError)
Gem Load Error is: AddDllDirectory failed for C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/pg-1.2.3/lib/x64-mingw32
...
... and many more error lines

Thanks in advance!

**Comment by larskanis** [comment]
This issue on Ruby-3.0 is still open. See #365 for workarounds.

**Comment by larskanis** [comment]
pg-1.3.0 is release, adding support for ruby-3.0 and 3.1 on Windows to the fat binary gems.
