### ISSUE TITLE
Add support for Pipeline mode of PostgreSQL-14

### ISSUE THREAD

**Issue by larskanis** [ged/ruby-pg#401]
This is a new execution mode of libpq that allows overlapping execution of queries. It is a client side change, that requires libpq of PostgreSQL-14, but all current PostgreSQL servers accept these overlapping queries. It is described here: https://www.postgresql.org/docs/14/libpq-pipeline-mode.html

There are 5 methods to be implemented for pipeline support as well as proper tests of this mode.

This ticket is about basic low level support for the pipeline mode only. Possibly there could be some convenience functions in the future and extensions to other libraries like ActiveRecord.

**Comment by jasoncodes** [comment]
> Add support for pipeline mode of PostgreSQL-14
This is interesting. Multiple concurrent queries on the same DB connection.
