### ISSUE TITLE
Move Travis CI (.com) from larskanis/ruby-pg to red-pg

### ISSUE THREAD

**Issue by tnir** [ged/ruby-pg#408]
While we are still able to see the CI results at https://app.travis-ci.com/github/larskanis/ruby-pg, we cannot see if the (Travis) CI pipeline fails in the pull requests.

We should move Travis CI (.com) from larskanis/ruby-pg to red-pg on travis-ci.com.

> Travis-CI is still running here: https://app.travis-ci.com/github/larskanis/ruby-pg

_Originally posted by @larskanis in https://github.com/ged/ruby-pg/issues/406#issuecomment-945158778_

**Comment by larskanis** [comment]
I removed Travis CI links from the README since the credit is repeatedly used up and I don't want to ask again and again for new support.
