### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jirutka** [ged/ruby-pg#409]
Can you please release a new version soon? The latest stable release is from Mar 18, 2020 and it’s not compatible with Ruby 3.0 (or PostgreSQL 14? :thinking:).

**Comment by larskanis** [comment]
Thank you for opening a dedicated issue for tracking the progress for pg-1.3.0!

pg-1.2.3 is compatible to ruby-3.0 and Postgresql-14. Only the windows binary gem doesn't support ruby3.0 but there are several workarounds.

Indeed we're quite close to a new release, which brings a lot of new additions and fixes. Still I'd like to add #401 before the next release and we should fix #404 and #398 first.

**Comment by Nodalailama** [comment]
Hi @larskanis,

Could you tell when you are planning to releases 1.3.0 version ? In months or weeks ?
Could you confirm me that this release will bring fiber async capacity ? and that mean bring to Rails app the possibility to use falcon finely ?

Cordialement,

**Comment by daBee** [comment]
`Ruby 2.7.4` is not supported on `MacOS Monterey 12.0.1` as OS dependencies are missing:
```
The following gems are missing OS dependencies:
 * date: /usr/lib/libSystem.B.dylib
 * nokogiri: /usr/lib/libSystem.B.dylib
 * nokogiri: /usr/lib/liblzma.5.dylib
 * nokogiri: /usr/lib/libobjc.A.dylib
 * pg: /usr/lib/libSystem.B.dylib
 * racc: /usr/lib/libSystem.B.dylib
```

**Comment by SamSaffron** [comment]
Oh... no longer working on Ruby 3.2 (latest trunk), we need a new gem to support testing on trunk @larskanis

**Comment by larskanis** [comment]
@SamSaffron There's already a ruby-3.2.0 compatible prerelease as discussed in #413 . Current release blocker is #398 and the pending release of rake-compiler-dock for support of ruby-3.1 binary gems.

**Comment by SamSaffron** [comment]
Awesome, thanks Lars!

**Comment by larskanis** [comment]
I just pushed `pg-1.3.0.rc2` to rubygems.org. This version fixes all release blockers and adjusts API documentation to the latest state. If no unexpected issues appear, I think the final 1.3.0 release can be made in the next few days.

/cc @ged

**Comment by guaguasi** [comment]
@larskanis This fixed an issue where my UUID primary key was being read as an integer in the web (`link_to foo` -> `/foos/1`) and web-console (`Foo.first` -> `id: 1`), but appeared fine in the rails console (`Foo.first` -> `id: 1ec7186f-335c-61c0-a804-9de580501a5e`).

I'm using Rails 7.0.1 and Ruby 3.1.

Thanks!

**Comment by ged** [comment]
Okay, thanks for all the hard work!

**Comment by yahonda** [comment]
Let me update that one behavior change https://github.com/ged/ruby-pg/commit/de18b88fb52caee4a40f7bc50b00717cc0ce42b8 between `pg-1.3.0.rc1` and `pg-1.3.0.rc2`  causes one of Ruby on Rails integration test failing. I have not created a minimum case yet, though.

**Comment by larskanis** [comment]
I just pushed pg-1.3.0.rc3 to rubygems.org fixing #415 and therefore https://github.com/rails/rails/issues/44146.

**Comment by yahonda** [comment]
I have confirmed rails/rails#44146 has been fixed by https://github.com/ged/ruby-pg/issues/415 and released as `pg-1.3.0.rc3` . Thanks for the fix.

**Comment by ged** [comment]
After working through a few issues with docker-machine and [newer versions of VirtualBox](https://www.virtualbox.org/ticket/20626), I finally have the binary Windows gems building on my machine. Now I just need to rebase against commits that have landed recently and I should have gems pushed this afternoon.

**Comment by ged** [comment]
v1.3.0 is pushed up to the gemservers.
