### ISSUE TITLE
Pipeline support breaks build

### ISSUE THREAD

**Issue by hennevogel** [ged/ruby-pg#429]
#403 breaks the build for me complaining about `PGRES_PIPELINE_SYNC` etc. being undeclared (and judging from a quick look at the PR it is). 

https://gist.github.com/hennevogel/d22b0e16a87b32914075754f700e0934

**Comment by larskanis** [comment]
The output tells that the version of libpq installed on your system is from PostgreSQL-14 while the header files are from an version 13. This doesn't work. Check if there is another libpq.so file in some system directory!

**Comment by hennevogel** [comment]
ARGH sorry for the noise...

![facepalm](https://media.giphy.com/media/Ll2p0718zZMhSHBXNd/giphy.gif)

**Comment by hennevogel** [comment]
@larskanis 💐
