### ISSUE TITLE
`certs/larskanis-2022.pem` in `pg-1.3.2.gem` has `0600` permissions

### ISSUE THREAD

**Issue by ojab** [ged/ruby-pg#432]
We're running CI inside a non-root container in GHA and copying installed gems to non-default directory in one of the jobs. Update to `pg-1.3.2` fails with
```
Run cp -r /app/vendor/bundle ./vendor/
cp: cannot open '/app/vendor/bundle/ruby/3.1.0/gems/pg-1.3.2/certs/larskanis-2022.pem' for reading: Permission denied
Error: Process completed with exit code 1.
```
and indeed the file has read permissions only for owner
```
I have no name!@810c6d69ef0b:/app$ ls -larth /app/vendor/bundle/ruby/3.1.0/gems/pg-1.3.2/certs/
total 16K
-rw------- 1 root root 1.6K Feb 15 10:13 larskanis-2022.pem
-rw-rw-r-- 1 root root 1.5K Feb 15 10:13 ged.pem
drwxr-xr-x 2 root root 4.0K Feb 15 10:13 .
drwxr-xr-x 7 root root 4.0K Feb 15 10:20 ..
```
Could you please make it the same as `ged.pem`, so similar workflows could work?

**Comment by larskanis** [comment]
You're right, the file in the gem has incorrect permissions. In contrast the permissions in the git repository are OK. I fixed the permission issue on my local computer, so that the next gem will be correct. Leaving this open to double check the next release.

**Comment by ojab** [comment]
Thanks, 1.3.3 works like a charm.
