### ISSUE TITLE
How to get results from multiple tables?

### ISSUE THREAD

**Issue by andresespinosapc** [ged/ruby-pg#436]
When I make a `SELECT` statement that contains fields from multiple tables, the `PG::Result` object returns the fields without any scope.

For example, if my query is something like this: `SELECT customers.first_name, users.first_name FROM customers, users WHERE customers.user_id = users.id`, when I get the `fields` from the result I get `["first_name", "first_name"]`.

How can I know which field is from which table?

**Comment by larskanis** [comment]
You can define custom column names like so:
```SQL
SELECT customers.first_name AS "customers.first_name", users.first_name AS "users.first_name" FROM customers, users WHERE customers.user_id = users.id
```

**Comment by cbandy** [comment]
@larskanis correct me if I'm wrong, but the columns of a result row/tuple are always in the same order as the `SELECT` statement.

@andresespinosapc in the query you provided,

```ruby
conn.exec('SELECT customers.first_name, users.first_name …') .each do |t|
  t[0] # always contains customers.first_name
  t[1] # always contains users.first_name
end
```
