### ISSUE TITLE
Segfault while connecting to PG from ruby sinatra

### ISSUE THREAD

**Issue by abhayranjan7** [ged/ruby-pg#448]
I have a web application using ruby 2.2.3 passenger 5.0.26 sinatra 1.4.6 on centOS-8. While making API requests PG.connect function is throwing seg fault error. Attaching the logs from passenger below. Can anyone please take a look and help.
Deployed code to server via `bundle exec cap deploy` command
Also let me know if any other detail is required. Thanks
[issueLog.log](https://github.com/ged/ruby-pg/files/8354286/issueLog.log)

**Comment by abhayranjan7** [comment]
@larskanis If possible, can you please take a look at this issue. Thanks

**Comment by larskanis** [comment]
There's not much I can do. The stack trace only shows that `PG.connect` segfaults. But there's no C level stack trace, which could lead to more detailed information. It could be some binary incompatibility with libpq or (more probably) with openssl. Also the versions are many years old.

The only hint I can give is to reinstall the pg gem.
