### ISSUE TITLE
PG::ConnectionBad: connection to server at "::1", when upgrading from 1.2.3 -> 1.3.1

### ISSUE THREAD

**Issue by jsnwesson** [ged/ruby-pg#452]
An issue that we've come across when upgrading from 1.2.3 to 1.3.1 is that for some people in my team, when trying to query into the production database (that we tunnel into), they receive this error: 
```
ActiveRecord::ConnectionNotEstablished: connection to server at "::1", port 9456 failed: Connection refused
    Is the server running on that host and accepting TCP/IP connections?

from /Users/jason/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
Caused by PG::ConnectionBad: connection to server at "::1", port 9456 failed: Connection refused
    Is the server running on that host and accepting TCP/IP connections?

from /Users/jason/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/pg-1.3.1/lib/pg/connection.rb:637:in `async_connect_or_reset'
```
We found that there's a potential threading issue that [occurs here](https://github.com/ged/ruby-pg/blob/9b7909d3d78c6ba2780427fab106d7c215ca300f/lib/pg/connection.rb#L153), as we've been able to resolve the `BadConnection` error by adding a simple `puts` immediately after this line. 

Is this an issue that you all have possibly seen before?

**Comment by larskanis** [comment]
Please update to the latest pg release! The ConnectionBad issue has probably been solved already.

**Comment by jsnwesson** [comment]
Hi @larskanis, we just tested making a query using 1.3.5, and we're getting the same issue as above.

**Comment by larskanis** [comment]
That's no threading issue. The inserted `put` just returns `nil` and disables name resolution in Ruby therefore. Then the name resolution is done in libpq, which sometimes is different for `localhost`.

Your tunnel obviously accepts only IPv4 connections, but `localhost` is resolved to IPv6.

You can adjust the name resolution to IPv4 or IPv6 by adding something like this to your `/etc/hosts` :
```
127.0.0.1 localhost
::1 localhost
```
Or you specify `127.0.0.1` in your connection string.

**Comment by larskanis** [comment]
I just noticed, that pg-1.2.3 tries to connect to both IPv4 and IPv6 addresses, if "localhost" resolves to both (which is usually the case, if "localhost" isn't defined in `/etc/hosts`).

In contrast pg-1.3.5 tries to connect to only the first address that is resolved from the hostname, which is usually the IPv6 address. Since your tunnel is only accessible by IPv4, the connection fails.

So there is a regression in pg-1.3.x. I'll fix this.

**Comment by jsnwesson** [comment]
Thanks for continuing to look into this! I'll let the team know to expect an update on this.
