### ISSUE TITLE
v1.3.0 breaks block-call semantics of PG::Connection

### ISSUE THREAD

**Issue by askreet** [ged/ruby-pg#454]
Looking at the code, it seems like an oversight, but `PG::Connection#initialize` was previously implemented entirely in C, ending with [this](https://github.com/ged/ruby-pg/blob/v1.2.3/ext/pg_connection.c#L282-L284) code:

```c
if (rb_block_given_p()) {
    return rb_ensure(rb_yield, self, pgconn_finish, self);
}
```

In v1.3.0, the class function `new` is replaced with Ruby code here.

```ruby
def new(*args, **kwargs)
	conn = self.connect_start(*args, **kwargs ) or
		raise(PG::Error, "Unable to create a new connection")

	raise(PG::ConnectionBad, conn.error_message) if conn.status == PG::CONNECTION_BAD

	conn.send(:async_connect_or_reset, :connect_poll)
end
```

The C implementation retains the semantics in `connect_start` (including a comment on 308 explaining it's role), but the block is not passed from `new` to `connect_start` in order to be called [on line 326](https://github.com/ged/ruby-pg/blob/master/ext/pg_connection.c#L326).

An example of some code that previously worked:

```ruby
PG::Connection.open(admin_database_url) do |c|
  c.exec("DROP DATABASE #{database_name}")
end
```

With v1.3.0 and later, the inner block is not called.

**Comment by larskanis** [comment]
Yes, this is an oversight. I'll fix this.
