### ISSUE TITLE
Confusion around PG::InvalidChangeOfResultFields error

### ISSUE THREAD

**Issue by coffenbacher** [ged/ruby-pg#468]
I seem to have stumbled across a rather unique error, so I'm having trouble finding information on Google about it.

For background, I'm using `.stream_each` to stream data out of a WAL slot so that I can process it:
```rb
def peek_sql
    sql = <<-SQL
    select data from pg_logical_slot_peek_changes(
      :slot_name, NULL, NULL,
      'format-version', '2',
      'include-timestamp', 'on',
      'include-transaction', 'true',
      'include-lsn','true',
      'include-pk', 'true',
      'write-in-chunks', 'true',
      'actions', 'insert,update,delete');
    SQL

    ApplicationRecord.sanitize_sql_for_assignment([sql, slot_name: slot_name])
end
```
```rb
    connection = ActiveRecord::Base.connection_pool.checkout
    connection.raw_connection.send_query(peek_sql)
    connection.raw_connection.set_single_row_mode
    connection.raw_connection.get_result.stream_each { |row| process_row(row) }
```

This is yielding this error:
```rb
/usr/src/app/app/commands/wal/archive.rb:28:in `stream_each': number of fields must not change in single row mode (PG::InvalidChangeOfResultFields)
```

I am struggling to gather more debug information because it is currently only happening in production, and it seems like the automatic retries we have configured allow the tricky data to succeed subsequently.

I am also not particularly sure what the semantic meaning of the error is: there is really only a single field (`data`) returned by the query so I'm confused how it's changing.

If it helps at all, I believe that this error was first seen soon after running a migration to add or remove a column.

Any information about what the error means or how to address it would be most welcome.

**Comment by larskanis** [comment]
The error InvalidChangeOfResultFields originates from here: https://github.com/ged/ruby-pg/blob/766c175879a7dd6a090b94f10a5932879d2bb533/ext/pg_result.c#L1481-L1482 This was meant as a precaution only, when I implemented the code, to get an early error, if this expectation fails.

The expectation that the number of columns shouldn't change originates from here: https://www.postgresql.org/docs/current/libpq-single-row-mode.html where it's stated:

> All of these PGresult objects will contain the same row description data (column names, types, etc) that an ordinary PGresult object for the query would have.

If I remember correctly, I didn't find a way to trigger that error, so that there is no spec to it. So congrats on finding such a case! :sweat_smile:

**Comment by larskanis** [comment]
It wasn't too difficult to find a test case. I'd like to add such a test case and extend the error message while being over it in #469.

Could it be that you have another query in `process_row` or somewhere else using the same connection object?

**Comment by larskanis** [comment]
@coffenbacher Did you find the root cause for InvalidChangeOfResultFields error? Can the ticket be closed?

**Comment by coffenbacher** [comment]
Hi @larskanis, this ticket can be closed, thanks! Unfortunately I never found out much more about what was going on. I think restarting my server resolved it IIRC.
