### ISSUE TITLE
High frequency of host lookups that return empty in CI with pg 1.4.0+

### ISSUE THREAD

**Issue by stanhu** [ged/ruby-pg#470]
After we upgraded our test suite to pg v1.4.0+ from v1.3.5, we started seeing a consistent pattern of host lookups that return empty in our CI environment. It appears we end up on this line: https://github.com/ged/ruby-pg/blob/252512608a814de16bbad55911f9bbcef0e73cb9/lib/pg/connection.rb#L740

We use a Docker service with the hostname `postgres`, and `errors` is empty so we only get a `PG::ConnectionBad` with no extra details provided. There should probably be an error that says something like, `Hostname "postgres" did not resolve to an IP address`.

I added some print messages (see below), and it appears when this failure happens `addrs` from this line return the empty set: https://github.com/ged/ruby-pg/blob/252512608a814de16bbad55911f9bbcef0e73cb9/lib/pg/connection.rb#L720

It seems to boil down to the difference between:

```ruby
# Used in pg v1.3.5
IPSocket.getaddress(mhost)
```

```ruby
# Used in pg v1.4.0+
Addrinfo.getaddrinfo(mhost, nil, nil, :STREAM)
```

For some reason in this Docker environment with Ubuntu-based images, the first method from v1.3.5 always works, but the second returns empty for some reason. Note that the empty set is different from a socket exception that is usually thrown when DNS fails:

```ruby
irb(main):004:0> Addrinfo.getaddrinfo('foo', nil, nil, :STREAM)
Traceback (most recent call last):
        6: from /usr/local/bin/irb:23:in `<main>'
        5: from /usr/local/bin/irb:23:in `load'
        4: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        3: from (irb):3
        2: from (irb):4:in `rescue in irb_binding'
        1: from (irb):4:in `getaddrinfo'
SocketError (getaddrinfo: Temporary failure in name resolution)
```

In our CI jobs, we have a Rake task that drops and resets the database with this gem, and this part of the job seems to work fine: DNS resolution appears to work, and PostgreSQL connections operate normally. It's only when the full Ruby on Rails tests start to run do we see a failure happen. It's possible we're doing something funny in our environment that triggers this behavior.

I monkey patched `Connection.connect_to_hosts` to print a few messages:

```ruby
        STDERR.puts "=== connect_to_hosts: ihosts are #{ihosts}"

        ihosts.each_with_index do |mhost, idx|
          unless host_is_named_pipe?(mhost)
            addrs = if Fiber.respond_to?(:scheduler) &&
                       Fiber.scheduler &&
                       RUBY_VERSION < '3.1.'

                      # Use a second thread to avoid blocking of the scheduler.
                      # `TCPSocket.gethostbyname` isn't fiber aware before ruby-3.1.
                      STDERR.puts "=== connect_to_hosts attempting getaddrinfo with thread"
                      Thread.new{ Addrinfo.getaddrinfo(mhost, nil, nil, :STREAM).map(&:ip_address) rescue [''] }.value
                    else
                      begin
                        ipsocket_addr = IPSocket.getaddress(mhost) rescue ''
                        STDERR.puts "=== connect_to_hosts ipsocket_addr: #{ipsocket_addr}"
                        STDERR.puts "=== connect_to_hosts attempting getaddrinfo"
                        res = Addrinfo.getaddrinfo(mhost, nil, nil, :STREAM)
                        STDERR.puts "=== connect_to_hosts addrinfo is #{res}"
                        res.map(&:ip_address)
                      rescue => e
                        STDERR.puts "=== connect_to_hosts Addrinfo rescue: #{e.inspect}"
                        ['']
                      end
                    end

            STDERR.puts "=== connect_to_hosts: addrs are #{addrs}"
```

I see:

```
=== connect_to_hosts: ihosts are ["postgres"]
=== connect_to_hosts ipsocket_addr: 172.17.0.3
=== connect_to_hosts attempting getaddrinfo
=== connect_to_hosts addrinfo is []
=== connect_to_hosts: addrs are []
```

Notice how the `IPSocket.getaddress` call worked fine, but the `Addrinfo.getaddrinfo` result simply returned a blank array.

On my local console, I tried to look at the Wireshark output to compare the DNS requests made, but I don't see any difference in the packet captures. I also looked at the underlying Ruby code, and I don't see any significant differences between the two. I may have to take some packet captures on the CI jobs themselves.

**Comment by stanhu** [comment]
Ok, this is a problem with our test environment. We seem to stub `Addrinfo.getaddrinfo`, and this is impacting the PostgreSQL DNS resolution. 🤦

**Comment by larskanis** [comment]
Scary story - luckily with an happy end!
