### ISSUE TITLE
Unexpected PG::UndefinedColumn error on GROUP BY

### ISSUE THREAD

**Issue by StanisLove** [ged/ruby-pg#475]
Hi, when I call
```ruby
User.select("coalesce(email, '00000@example.com') as user_email").group(:user_email)
```
It raises an `PG::UndefinedColumn` error

But if I do the same in plain SQL
```sql
SELECT coalesce(email, '00000@example.com) AS user_email GROUP BY user_email
```
It doesn't
Is it a correct behavior that I've got the error?

Tested with Postgres v11, v13 and pg v1.4.1

**Comment by fatkodima** [comment]
@StanisLove Can you create a reproducible test script?

**Comment by larskanis** [comment]
Sorry for the late answer, but this is a rails issue. You can use `User.find_by_sql("SELECT ... GROUP BY ...")` or check the rails docs for more elegant solutions. ActiveRecord has a lot of different ways to do things.
