### ISSUE TITLE
Value for the #host method is wrong

### ISSUE THREAD

**Issue by dima4p** [ged/ruby-pg#477]
Hello, I've got a very strange value for PG::Connection#host.

```
$ bec                                                                                           
Loading development environment (Rails 7.0.3.1)                                                 
3.1.1 :001 > rc = ::ActiveRecord::Base.connection_pool.with_connection{|conn| conn.raw_connectio
n}
 => #<PG::Connection:0x00007f26bdcb2970 @calls_to_put_copy_data=0, @last_status=4> 
3.1.1 :002 > rc.host
 => "/tmp" 

```
Is it a bug or feature?
And how to get the real host?

**Comment by larskanis** [comment]
You're using a UnixSocket connection to a local PostgreSQL server. The socket file is probably:
```
/tmp/.s.PGSQL.5432
```
but the user selectable part is the directory only. This is what PG::Connection#host returns.

**Comment by dima4p** [comment]
> You're using a UnixSocket connection to a local PostgreSQL server. The socket file is probably:
> 
> ```
> /tmp/.s.PGSQL.5432
> ```
> 
> but the user selectable part is the directory only. This is what PG::Connection#host returns.

Why is not `/.s.PGSQL.5432` included?

**Comment by cbandy** [comment]
> Why is not `/.s.PGSQL.5432` included?

See `host` here: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-HOST

**Comment by dima4p** [comment]
Thanks
