### ISSUE TITLE
Issue with using it in AWS Lambda functions

### ISSUE THREAD

**Issue by sridharraman** [ged/ruby-pg#489]
I tried using the pg gem for connecting to an RDS database from an AWS Lambda function. Unfortunately, the function throws an error like this:

`"errorMessage": "libpq.so.5: cannot open shared object file: No such file or directory - /var/task/vendor/bundle/ruby/2.7.0/gems/pg-1.4.4/lib/pg_ext.so",`

When I checked online, they recommend setting up a docker-lambda instance that installs postgresql as well. Is there no way of using this gem without having postgresql installed? I am using it to connect to a remote database, would I still need postgresql installed?

Interestingly, a similar library in node.js (pg) works fine as it doesn't seem to need additional dependencies. Is there anything I can do (apart from moving my lambda code from ruby to js?)

**Comment by larskanis** [comment]
You must install libpq in order to use the pg.gem (the full postgresql server installation isn't necessary), which is kind of
```sh
sudo apt install libpq-dev 
```
or so. This is similar to the mysql2.gem. There are certainly proper ways to do this in AWS Lambda.

**Comment by larskanis** [comment]
This will probably solved when #480 is implemented.
