### ISSUE TITLE
No connection to the server after a period of time

### ISSUE THREAD

**Issue by kirqe** [ged/ruby-pg#494]
I'm constantly getting one of the following errors(but it seems they're the same) after a day or 2 of activity

This is a tiny Sinatra app running in a pod. The activity is requests every 4-5 seconds that add 1-4 records to the db

```
ActiveRecord::StatementInvalid
PG::ConnectionBad: PQsocket() can't get socket descriptor

ActiveRecord::StatementInvalid
PG::UnableToSend: no connection to the server
```

Some people suggested adding `reconnect: true` or `reaping_frequency: 10` but it doesn't seem to work https://discuss.circleci.com/t/pg-connectionbad-pqsocket-cant-get-socket-descriptor/470

There's also this post suggesting updating the `tcp_keepalives..` configs https://github.com/ged/ruby-pg/issues/247#issuecomment-539692988 (haven't tried this)

Another post suggested adding a health checker route which checks the connection and does something like this
```
ActiveRecord::Base.connection.execute('SELECT 1;')
rescue StandardError
ActiveRecord::Base.connection.reconnect!
```

Thought it was related to puma. It used to be running in the phased mode with 2 workers. At this moment I commented the workers option in the puma.rb

```
ruby '3.1.2'
pg (1.4.5)
sinatra (2.2.0)
sinatra-activerecord (2.0.25)
```

**Comment by larskanis** [comment]
On which operating system is it running?

These kind of issues happen usually only if there's no direct connection between the pg client and the PostgreSQL server. Is there any load-balancer in between. Or a firewall with NAT? In that case it's actually best to use the `tcp_keepalive` settings and/or some kind of health checker. If I remember right, this is already builtin into ActiveRecord.

There errors don't look like a connection pool exhaustive.

**Comment by kirqe** [comment]
It's running in a k8s pod. I used `ruby:3.1.2-slim` docker image that I believe uses `debian:buster-slim`

**Comment by kirqe** [comment]
I didn't work :/
