### ISSUE TITLE
Possibility to return multiple values on insert

### ISSUE THREAD

**Issue by quadlol** [ged/ruby-pg#495]
In my case, I have database triggers that generate some unique fields on insert, such as "document_number". 

Now, whenever I create a record in ruby, eg. I have to reload the object to see the field. I guess this is caused by the `RETURNING id` clause. Is there a way how to extend this behavior to return `RETURNING id, document_number` after each insert?

```
a = Document.new
a.document_number == nil
a.reload
a.document_number != nil
```

**Comment by larskanis** [comment]
Sorry, this is not answered, since it's a rails question. Not something about ruby-pg.
