### ISSUE TITLE
Release pg-1.5.0

### ISSUE THREAD

**Issue by larskanis** [ged/ruby-pg#512]
I added a [bunch of new features](https://github.com/ged/ruby-pg/blob/master/History.md#v150-yyyy-mm-yy-lars-kanis-larsgreiz-reinsdorfde) to be released as pg-1.5.0.

@ged , @cbandy Any objections about a new release? Anything you would like to get into pg-1.5.0?

**Comment by ged** [comment]
No, I'm 👍 .

**Comment by cbandy** [comment]
Sounds good to me! 👍🏻

**Comment by larskanis** [comment]
pg-1.5.0 is out and already pg-1.5.1 with a fix of minor regression in rails.

**Comment by larskanis** [comment]
@ged Could you please update [docs](https://deveiate.org/code/pg/README_md.html) for pg-1.5?

**Comment by ged** [comment]
> @ged Could you please update [docs](https://deveiate.org/code/pg/README_md.html) for pg-1.5?

Done.
