### ISSUE TITLE
`certs/larskanis-2023.pem` in version 1.4.6 has 0600 permissions

### ISSUE THREAD

**Issue by bcrivelaro** [ged/ruby-pg#520]
**Similar to https://github.com/ged/ruby-pg/issues/432, but now with the 2023 certificate.**

We are currently running CI inside a non-root container in GHA and copying installed gems to non-default directory in one of the jobs. Using version 1.4.6, we got the following error:

```
Run cp -r /app/vendor/bundle ./vendor/
cp: cannot open '/app/vendor/bundle/ruby/3.1.0/gems/pg-1.4.6/certs/larskanis-2023.pem' for reading: Permission denied
Error: Process completed with exit code 1.
```

Checking the permissions for this file, we got:
![image](https://user-images.githubusercontent.com/23528218/230251970-08140e42-6800-4225-92a5-d9aec438c5f7.png)

May we ask you to please change the permissions for the `larskanis-2023.pem` to make it the same as 2022?

**Comment by larskanis** [comment]
I'll fix this in pg-1.5.0 soon.
