### ISSUE TITLE
failed to install pg 1.4.6 on Centos7 with ruby 3.2.0, whereas with ruby 3.1.0 it installs 

### ISSUE THREAD

**Issue by ganimedes** [ged/ruby-pg#533]
$  gem install pg -v '1.4.6' --source 'https://rubygems.org/'
Building native extensions. This could take a while...
ERROR:  Error installing pg:
	ERROR: Failed to build gem native extension.

    current directory: /home/nachwuchskraefte/.rvm/gems/ruby-3.2.0/gems/pg-1.4.6/ext
/home/nachwuchskraefte/.rvm/rubies/ruby-3.2.0/bin/ruby -I /home/nachwuchskraefte/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0 extconf.rb
Calling libpq with GVL unlocked
checking for pg_config... yes
Using config values from /usr/pgsql-14/bin/pg_config
Using libpq from /usr/pgsql-14/lib
checking for libpq-fe.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

$ yum list installed | grep postgresql14-devel
postgresql14-devel.x86_64             14.7-1PGDG.rhel7           @pgdg14

**Comment by damuz91** [comment]
you are missing to install postgresql-devel 
```sudo dnf install postgresql-devel```
The postgresql-devel package contains the header files and libraries needed to compile C or C++ applications which will directly interact with a PostgreSQL database management server and the ecpg Embedded C Postgres preprocessor. You need to install this package if you want to develop applications which will interact with a PostgreSQL server.

**Comment by ganimedes** [comment]
Thank you for the answer. But postgresql-devel is already installed:
# yum list installed | grep postgresql14-devel
postgresql14-devel.x86_64             14.8-1PGDG.rhel7           @pgdg14   
Since postgresql14 is running on my server, the postgresql14-devel must be installed, where pg 1.4.6 is not compatible. The only solution would be to downgrade to postgresql13, or to fix the problem in pg 1.4.6.

**Comment by larskanis** [comment]
As written in the log output: `Check the mkmf.log file for more details.` would help. But this looks like outdated.
