### ISSUE TITLE
How to build an old pg on ruby 2.3.1

### ISSUE THREAD

**Issue by singlewind** [ged/ruby-pg#534]
We have an old rails application based on ruby 2.3.1 and our pg version is 0.20.0. When we upgrade the base image from jessie to bulleyes. We are unable to connect postgresql database in sslmode. The error is below. 

/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651: [BUG] Segmentation fault at 0x00000000000000

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

Environment:
Ruby: 2.3.1 built from ruby-build
Bundle: 1.17.0
Rails: 4.2.11.1
PG: 0.20.0 by bundle

No errors during build.

**Comment by larskanis** [comment]
All these versions are outdated.

**Comment by carchrae** [comment]
@singlewind - did you ever find a solution?  i'm also stuck with a legacy rails project that needs to be moved to a new server and pg is causing so much grief.  upgrading the versions is all well and good, but brings a whole load of pain.  i think it is linking to a modern postgres dev lib that is causing the crash.  i've installed the old postgres version, but i suspect the latest OS is giving a modern binding.   (and yes, i did try using a modern version of postgres first, and a modern version of pg)

(and @larskanis - absolutely reasonable that you don't want to support a version that is 10 years old)
