### ISSUE TITLE
Segmentation fault in ruby:3.2.2-alpine3.18 docker image

### ISSUE THREAD

**Issue by imamdg** [ged/ruby-pg#540]
While trying to deploy an app with base image `ruby:3.2.2-alpine3.18`, I was facing the following error. It was working fine with docker compose in Macbook m2 pro.

```
/usr/local/bundle/gems/pg-1.4.6/lib/pg/connection.rb:627: [BUG] Segmentation fault at 0x00000001000001b7

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux-musl]

-- Control frame information -----------------------------------------------
c:0045 p:---- s:0270 e:000269 CFUNC :connect_poll
c:0044 p:0358 s:0266 e:000265 METHOD /usr/local/bundle/gems/pg-1.4.6/lib/pg/connection.rb:627
c:0043 p:0265 s:0253 e:000252 METHOD /usr/local/bundle/gems/pg-1.4.6/lib/pg/connection.rb:761
c:0042 p:0007 s:0242 e:000241 METHOD /usr/local/bundle/gems/pg-1.4.6/lib/pg/connection.rb:696
```

After a series of trial and error, we managed to resolve the issue by downgrading the Ruby Docker image to `ruby:3.2.2-alpine3.16`.   `ruby:3.2.2-alpine3.17` also has the same problem.

**Comment by drdrsh** [comment]
It will probably help if you can provide a Minimal reproducible example that demonstrates the issue

**Comment by jcdennen** [comment]
there seem to be a crop of seg faults recently, I wonder if they're related. have you tried the fix proposed in this issue? https://github.com/ged/ruby-pg/issues/538#issuecomment-1701749879
