### ISSUE TITLE
conn.exec writing "INFO" statements to stderr instead of stdout

### ISSUE THREAD

**Issue by trak3r** [ged/ruby-pg#552]
Setup
```ruby
    connection = PG.connect( ...
```
Execute
```ruby
    connection.exec <<~SQL
      COPY dev.public.#{table_name}
      FROM 's3://#{redshift_bucket_name}/#{csv_file_name}'
```
Results
```bash
bundle exec rails redshift:sync

RESULT CODE: 0

ERROR OUTPUT:
INFO:  Load into table 'xxx' completed, 15430 record(s) loaded successfully.

STANDARD OUTPUT:
```
How do I get those "INFO" statements directed to standard output so they aren't interpreted as errors and script failure?
Thanks!

**Comment by larskanis** [comment]
You can use [set_notice_receiver](https://deveiate.org/code/pg/PG/Connection.html#method-i-set_notice_receiver) or [set_notive_processor](https://deveiate.org/code/pg/PG/Connection.html#method-i-set_notice_processor) to suppress the messages. something like this:

```ruby
c = PG.connect
c.set_notice_processor{|msg| p msg }  # catch massages
c.exec("DO $$ BEGIN RAISE INFO 'message 1'; END; $$ LANGUAGE plpgsql")
c.set_notice_processor    # back to default - printing to stderr
```
 
You're using Windows Powershell? It has the feature to recognize stderr output as a failure.

**Comment by trak3r** [comment]
Thank you @larskanis
