### ISSUE TITLE
Binary Windows gem no longer available for Ruby v3.3 since v1.5.6

### ISSUE THREAD

**Issue by andyundso** [ged/ruby-pg#573]
Can be seen on Rubygems.

* [v1.5.5](https://rubygems.org/gems/pg/versions/1.5.5-x64-mingw-ucrt) (where support was introduced): version range is listed as `>= 3.1, < 3.4.DEV`.
* [v1.5.6](https://rubygems.org/gems/pg/versions/1.5.6-x64-mingw-ucrt): version range is listed as `>= 3.1, < 3.3.DEV`.

**Comment by larskanis** [comment]
This is unintended. I'll fix it with 1.5.7.

**Comment by larskanis** [comment]
OK, pg-1.5.7 is released with this fix.
